spring:
  application:
    name: HumanResourceDemo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: false
  jwt:
    secret-key: N53ZENIJOWDgPbtvesRkV39ug8HeJljb5qYcPRx9F9A=
