spring:
  config:
    import: file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: false
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
