spring:
  config:
    import: file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: false
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  docker:
    compose:
      lifecycle-management: start_only
mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
#logging:
#  level:
#    org.springframework.data: DEBUG
#    org.hibernate: DEBUG
jwt:
  expiration:
    duration: 600000